export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  PRODUCTS: "/dashboard/products",
  PRODUCTS_NEW: "/dashboard/products/new",
  PRODUCTS_EDIT: "/dashboard/products/:id/edit",
  CATEGORIES: "/dashboard/categories",
  QUOTES: "/dashboard/quotes",
  QUOTES_DETAIL: "/dashboard/quotes/:id",
  USERS: "/dashboard/users",
  USERS_NEW: "/dashboard/users/new",
  USERS_EDIT: "/dashboard/users/:id/edit",
  ANALYTICS: "/dashboard/analytics",
  SETTINGS: "/dashboard/settings",
  UNAUTHORIZED: "/unauthorized",
  NOT_FOUND: "*",
};
